name: local_history
description: A sample command-line application.
version: 1.0.0-dev.1
repository: https://github.com/kingwill101/local_history
executables:
  lh: local_history

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  artisanal: ^0.1.0-dev+5
  ormed: ^0.1.0-dev+6
  ormed_sqlite: ^0.1.0-dev+6
  ormed_cli: ^0.1.0-dev+6
  contextual: ^2.0.0
  crypto: ^3.0.3
  dart_mcp: ^0.4.0
  yaml: ^3.1.3
  glob: ^2.1.3
  watcher: ^1.2.0
  deviation: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.4
